---
title: Welcome to Homework 2
date: last-modified
author: Dominic Mason
format:
    gfm:
        mermaid-format: png
---

This is my solution to homework 2. I'm using Quarto render this document from a QMD file to a regular
MD file for display on GITHUB.

## Scenario

Imagine you're designing a Library Management System for a small local library. The system needs to track information about books and library members. Each book has a unique ISBN (International Standard Book Number), a title, and a publication year. Each library member is identified by a unique member ID, and the system needs to store their name and contact information. Library members can check out books, but they don’t have to.

## Design Task 1

Identify and document the entities, attributes, and relationships using Chen notation.

```{dot}
//| echo: false
graph LibraryManagementSystem {
    layout=neato;
    scale=1.1;
    node [shape=box]; LibraryMember; Book;
    node [shape=ellipse]; ISBN; Title; PublicationYear; MemberID; Name; ContactInfo;
    node [shape=diamond,style=filled,color=lightgrey]; Checkout
    
    Book -- Checkout [label="n",len=1.50]
    LibraryMember -- Checkout [label="can",len=1.50]
    
    
    LibraryMember -- MemberID
    LibraryMember -- Name
    LibraryMember -- ContactInfo
    Book -- ISBN
    Book -- Title
    Book -- PublicationYear
  
}
```

## Design Task 2

Identify and document the entities, attributes, and relationships using Crow’s Foot notation.

<center>

::: {.column}
```{mermaid}
erDiagram
    LibraryMember ||--|{  Book : canCheckout

    Book{
    string ISBN
    string Title
    string PublicationYear
    }

    LibraryMember{
    string MemberID
    string Name
    string ContactInformation
    }
```
:::
